version: '2.2'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es1
    command: elasticsearch -Enetwork.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - node.name=es1
        - cluster.name=docker-cluster
        - discovery.seed_hosts=es1,es2,es3,es4
        - cluster.initial_master_nodes=es1,es2,es3,es4
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    restart: always

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es2
    command: elasticsearch -Enetwork.host=0.0.0.0
    environment:
        - node.name=es2
        - cluster.name=docker-cluster
        - discovery.seed_hosts=es1,es2,es3,es4
        - cluster.initial_master_nodes=es1,es2,es3,es4
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    restart: always

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es3
    command: elasticsearch -Enetwork.host=0.0.0.0
    environment:
        - node.name=es3
        - cluster.name=docker-cluster
        - discovery.seed_hosts=es1,es2,es3,es4
        - cluster.initial_master_nodes=es1,es2,es3,es4
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    restart: always
  
  es4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es4
    command: elasticsearch -Enetwork.host=0.0.0.0
    environment:
        - node.name=es4
        - cluster.name=docker-cluster
        - discovery.seed_hosts=es1,es2,es3,es4
        - cluster.initial_master_nodes=es1,es2,es3,es4
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    restart: always


networks:
  esnet: